server:
  port: 9090
  servlet:
    context-path: /ivy-root

# 驱动配置信息
spring:
  http:
    multipart:
      location: /data/upload_tmp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ivy-root
#        uri: mongodb://localhost:27017/ivy-root
  cache:
    type: ehcache
    ehcache:
      config: classpath:cache/ehcache.xml
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ivy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false

    username: root
    password: Boya@2019
    driverClassName: com.mysql.cj.jdbc.Driver
#连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data
#

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ivy.root.domain,com.ivy.root.wechat.domain
  #pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
wechat:
  appId: wx44f8131ace479c8e
  appSecret: ce88823d0c5de38245f93ebe93d97b40
  urlGetAccessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET

img:
  location: /upload
  proportion: 0.2f

logging:
  path: /boya/ivy-root/log
  level:
    com.ivy.root: info
